export const String = {
    moon: 'Moon',
    note: 'Note',
    subHeader: 'Notebook and Reminder',
    signUp: 'Sign Up',
    logIn: 'Log In',
    emailIDPlaceholder: 'Email ID',
    emailID: 'email',
    userName: 'userName',
    password: 'password',
    confiremPasswordPlaceolder: 'Confirm Password',
    confiremPassword: 'ConfirmPassword',
    or: 'Or',
    signInHere: 'Sign in Here',
    loginWithGoogle: 'Log In with Google',
    loginWithFacebook: 'Log In with Facebook',
    signupWithEmail: 'Sign up with Email',
    forgotPassword: 'Forgot Password?',
    notebook: 'Notebook',
    reminder: 'Reminder',
    today: 'Today',
    tomorrow: 'Tomorrow',
    everyday: 'Everyday',
    createNoteHeader:'Create New Note',
    unTitle: 'Untitle',
    typeHere: 'Type Here',
    addReminder: 'Add Reminder',
    on: 'On',
    time: 'Time',
    am: 'AM',
    pm: 'PM',
    choose: 'Choose',
    addNote: 'Add Note',
    notes: 'Notes',
    reminders: 'Reminders',
    deleted: 'Deleted',
    archives: 'Archives',
    rateOurApp: 'Rate our app',
    shareOurApp: 'Share our app',
    giveUsFeedback: 'Give us a feedback',
    logOut: 'Log Out',
    noNoteFound: 'No Note Found',
    noRemindersFound: 'No Reminders Found',
    untitle: 'Untitle',
    noNoteSelected: 'No Note Selected',
    tenMin: '10 Min',
    thirtyMin: '30 Min',
    oneHour: '1 Hour',
    pastReminder: 'Past Reminder',
    ok: 'OK',
    cancle: 'Cancle',
    alert: 'Alert',
    
    //success Messages
    signUpSuccess: 'Sign up successfully',
    logInSuccess: 'Log in successfully',
    noteAdded: 'Note added successfully',
    noteUpdated: 'Note updated successfully',
    noteDeleted: 'Note deleted successfully',
    noteRestored: 'Note restored successfully',
    logOutSuccess: 'Log out successfully',
    logOutMessage: 'Are you sure you want to log out?',
    deleteNoteMessage: 'Are you sure you want to delete selected notes?',
    deleteReminderMessage: 'Are you sure you want to delete selected reminders?',
    backActionMessage: 'Are you sure you want exit the app?',

    //error messages
    emailIDRequired: 'Email ID is required',
    emailIDInvalid: 'Email ID is invalid',
    userNameRequired: 'Username is required',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 4 characters',
    confirmPasswordRequired: 'Confirm Password is required',
    confirmPasswordMatch: 'Passwords did not match',
    noteTitleRequired: 'Note title is required',
    logInFailed: 'Log in failed',
    loginError: 'Login Error',
    invalidCredentials: 'Invalid credentials',
    emailExitLogin: 'Email already exist, please login',
    weakPassword: 'Password is too weak',
    signupError: 'Signup Error',
    userNotFound: 'User not found',
    titledescIsRequired: 'Title and Description is required',
    errorFetchedNotes: 'Error in fetching notes',
    reminderAdded: 'Reminder added successfully',
    reminderDeleted: 'Reminder deleted successfully',
    reminderUpdated: 'Reminder updated successfully',
    errorFetchedReminders: 'Error in fetching reminders',
    selectedTimePassed: 'Selected time has already passed',

    //provider
    google: 'Google',
    facebook: 'Facebook',
    emailPassword: 'EmailPassword',
} as const;